using Microsoft.AspNetCore.Mvc;
using SangataWeb.Models;

namespace SangataWeb.Class
{
    public interface IGetData
    {
        Task<ActionResult<Users>>? ApiLogin();
        Task<ActionResult<List<Users>>>? ApiUserAll();
        Task<ActionResult<List<AssetMain>>>? ApiAssetMain(string typ, string aID);
        Task<ResultJson>? ApiAssetMainChecking(AssetMain main);
        Task<ActionResult<AssetMain>>? ApiAssetMainBy(ActionModelData actionModel);
        Task<ActionResult<List<ServicePrice>>>? ApiServicePrice();
        Task<ActionResult<List<Technician>>>? ApiTechnician();
        Task<ActionResult<List<Technician>>>? ApiTechnicianRate();
        Task<ActionResult<List<Project>>>? ApiProject();
        Task<ActionResult<List<RepairGroup>>>? ApiRepairGroup();
        Task<ActionResult<List<Service>>>? ApiService(string sAssetID);
        Task<ActionResult<List<Repair>>>? ApiRepair(string sAssetID);
        Task<ActionResult<List<AssetMain>>>? ApiAssetMainFind();
        Task<ActionResult<DailyRequest>>? ApiDailyRequest();
        Task<ActionResult<List<DailyRequestLabour>>>? ApiDailyRequestLabour(string drRefNo);
        Task<ActionResult<List<DailyRequestMaterial>>>? ApiDailyRequestMaterial(string drRefNo);
        Task<ResultJson>? ApiAssetRequestChecking(DailyRequest daily);
        Task<ActionResult<List<Store>>>? ApiStore();
        Task<ActionResult<Store>>? ApiOneStore();
        Task<ActionResult<DailyRequest>>? ApiRequestBy(ActionModelData actionModel);
        Task<ActionResult<List<DailyRequest>>>? ApiRequestFind();
        Task<ActionResult<List<ClientRef>>>? ApiClientRef();
        Task<ActionResult<List<Location>>>? ApiLocation();
        Task<ActionResult<List<Customer>>>? ApiCustomer();
        Task<ActionResult<List<OrderType>>>? ApiOrderType();
        Task<ActionResult<List<CompleteBy>>>? ApiCompleteBy();
        Task<ActionResult<Repair>>? ApiOneRepair();
        Task<ResultJson>? ApiMainChecking(Repair main);
        Task<ActionResult<Repair>>? ApiMainBy(ActionModelData actionModel);
        Task<ActionResult<List<Repair>>>? ApiMainFind();
        Task<ActionResult<Repair>>? ApiRepairRequest();
        Task<ActionResult<List<Repair>>>? ApiRepairFind();
        Task<ActionResult<List<CCSCode>>>? ApiCCSCode();
        Task<ActionResult<List<CCSCodeNew>>>? ApiCCSCodeNew();
        Task<ActionResult<List<Unit>>>? ApiUnit();
        Task<ActionResult<List<Rack>>>? ApiRack();
        Task<ActionResult<List<Bin>>>? ApiBin();
        Task<ActionResult<StoreSum>>? ApiStoreSum(string sStockCode);
        Task<ResultJson>? ApiStoreChecking(Store main);
        Task<ActionResult<Store>>? ApiStoreBy(ActionModelData actionModel);
        Task<ActionResult<List<Store>>>? ApiStoreFind();
        Task<ActionResult<DailyRequest>>? ApiStoreRequest();
        Task<ActionResult<List<vWINo>>>? ApiJob(int id);
        Task<ActionResult<vWINo>>? ApiJobOne(int id);
        Task<ActionResult<List<Foreman>>>? ApiForeman();
        Task<ActionResult<List<StoreMan>>>? ApiStoreMan();
        Task<ActionResult<DailyRequest>>? ApiRequestStoreBy(ActionModelData actionModel);
        Task<ActionResult<List<PreparedBy>>>? ApiPreparedBy();
        Task<ActionResult<InternalReqOUT>>? ApiOneRequest();
        Task<ActionResult<List<Currency>>>? ApiCurrency();
        Task<ActionResult<List<RecBy>>>? ApiRecBy();
        Task<ResultJson>? ApiAssetIRequestOutChecking(InternalReqOUT daily);
        Task<ActionResult<List<InternalReqSubOUT>>>? ApiDailyIRequestSubOut(string irosNo);
        Task<ActionResult<List<InternalReqOUT>>>? ApiIRequestOutFind();
        Task<ActionResult<InternalReqOUT>>? ApiIRequestOutBy(ActionModelData actionModel);
        Task<ActionResult<List<ListMaterialOutSummary>>>? ApiListMaterialOutSummary(string key = "");
        Task<ActionResult<List<ListMaterialOut>>>? ApiListMaterialOut(string key = "");
        Task<ActionResult<InternalReq>>? ApiOneRequestIn();
        Task<ActionResult<List<InternalReqSub>>>? ApiDailyIRequestSubIn(string irsNo);
        Task<ActionResult<List<InternalReq>>>? ApiIRequestInFind();
        Task<ResultJson>? ApiAssetIRequestInChecking(InternalReq daily);
        Task<ActionResult<InternalReq>>? ApiIRequestInBy(ActionModelData actionModel);
        Task<ActionResult<List<SupplierList>>>? ApiSupplierList();
        Task<ActionResult<Adjustment>>? ApiAdjustment();
        Task<ActionResult<List<AdjustmentSub>>>? ApiAdjustmentSub(string adNo);
        Task<ActionResult<List<Adjustment>>>? ApiAdjustmentFind();
        Task<ResultJson>? ApiAdjustmentChecking(Adjustment daily);
        Task<ActionResult<Adjustment>>? ApiAdjustmentBy(ActionModelData actionModel);
        Task<ActionResult<Shipping>>? ApiShipping();
        Task<ActionResult<List<vShippingSub>>>? ApiShippingSub(string sisNo);
        Task<ActionResult<List<FreightType>>>? ApiFreightType();
        Task<ActionResult<List<vShippingPONo>>>? ApiShippingPONo();
        Task<ActionResult<List<Shipping>>>? ApiShippingFind();
        Task<ActionResult<List<vStoreIssueSub>>>? ApiStoreIssueSub(string sisNo);
        Task<ActionResult<List<vOrReqNo>>>? ApiOrReqNo();
        Task<ResultJson>? ApiShippingChecking(Shipping daily);
        Task<ActionResult<Shipping>>? ApiShippingBy(ActionModelData actionModel);
        Task<ActionResult<Docket>>? ApiDocket();
        Task<ActionResult<List<vDocketSub>>>? ApiDocketSub(string ddsNo);
        Task<ActionResult<List<Docket>>>? ApiDocketFind();
        Task<ResultJson>? ApiDocketChecking(Docket daily);
        Task<ActionResult<Docket>>? ApiDocketBy(ActionModelData actionModel);
        Task<ActionResult<BackCharge>>? ApiBackCharge();
        Task<ActionResult<List<BackChargeSub>>>? ApiBackChargeSub(int? bsKPCReqNo);
        Task<ActionResult<List<BackCharge>>>? ApiBackChargeFind();
        Task<ResultJson>? ApiBackChargeChecking(BackCharge daily);
        Task<ActionResult<BackCharge>>? ApiBackChargeBy(ActionModelData actionModel);
        Task<ActionResult<List<StockIn>>>? ApiStockIn(string code);
        Task<ActionResult<List<StockOut>>>? ApiStockOut(string code);
        Task<ActionResult<Store>>? ApiStockDetailBy(ActionModelData actionModel);
        Task<ActionResult<List<ReportMaster>>>? ApiReportMaster();
        Task<ActionResult<ReportMaster>>? ApiOneReportMaster(int Id);
        Task<ActionResult<List<DropDownReport>>>? ApiDropDownReport(string tbl, string clm1, string clm2);
        Task<IQueryable<string>>? ApiListReport(string query);
    }
}
